# Generated by Django 6.1 on 2026-08-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='github_link',
            new_name='project_link',
        ),
    ]
