# Generated by Django 6.1 on 2026-08-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_github_link_portfolio_project_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
