# Generated by Django 6.1 on 2026-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolio_options_portfolio_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='portfolioapp/demo/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolioapp/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='portfoliofile',
            name='main_file',
            field=models.FileField(upload_to='portfolioapp/project_file/'),
        ),
    ]
