# Generated by Django 6.1 on 2026-08-13 04:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_portfolio_demo_video_alter_portfolio_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='demo_video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='portfolioapp/demo/'),
        ),
        migrations.AlterField(
            model_name='portfoliofile',
            name='main_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='portfolioapp/project_file/'),
        ),
    ]
