# Generated by Django 6.1 on 2026-09-02 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_portfolio_demo_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('visit', models.IntegerField()),
                ('ip_address', models.CharField(max_length=42)),
                ('user_agent', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-priority', '-created_date']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Visit count'),
        ),
    ]
