# Generated by Django 6.1 on 2026-09-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visitorinfo_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorinfo',
            name='visit',
        ),
    ]
