# Generated by Django 6.1 on 2026-09-02 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_visitorinfo_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVisitInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=42)),
                ('user_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_visits', to='core.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
