# Generated by Django 6.1 on 2026-09-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projectvisitinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='visit_count',
        ),
    ]
