# Generated by Django 6.1 on 2026-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_portfolio_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvisitinfo',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
