# Generated by Django 6.1 on 2026-10-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_projectvisitinfo_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
