"""
Django settings for myportfolio project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv, dotenv_values
import dj_database_url
import cloudinary

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if os.environ.get("DJANGO_SECURITY_KEY"):
    SECRET_KEY = os.environ.get("DJANGO_SECURITY_KEY")
else:
    SECRET_KEY = os.getenv("DJANGO_SECURITY_KEY_local")

# SECURITY WARNING: don't run with debug turned on in production!
# if os.getenv("django_local"):
#     DEBUG = True
# else:
#     DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    #'cloudinary_storage',      # Conflicts with whitenoise, when doing collectstatic
    'cloudinary',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',

    'tailwind',
    'theme',
]

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myportfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myportfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
if os.environ.get('pg_endpoint'):    # Postgres
    pg_config = dj_database_url.parse(os.environ.get('pg_endpoint'))     # Parse params for neondb

    DATABASES = {
        'default': {
            'ENGINE': pg_config['ENGINE'],
            'NAME': pg_config['NAME'],
            'USER': pg_config['USER'],
            'PASSWORD': pg_config['PASSWORD'],
            'HOST': pg_config['HOST'],
            'OPTIONS': pg_config['OPTIONS'],
            'PORT': pg_config['PORT']
        },
    }
else:                   # Sqlite3
    pg_config = dj_database_url.parse(os.getenv('pg_endpoint_local'))     # Parse params for neondb

    DATABASES = {
        'default': {
            'ENGINE': pg_config['ENGINE'],
            'NAME': pg_config['NAME'],
            'USER': pg_config['USER'],
            'PASSWORD': pg_config['PASSWORD'],
            'HOST': pg_config['HOST'],
            'OPTIONS': pg_config['OPTIONS'],
            'PORT': pg_config['PORT']
        },
    }


# For media storage - Cloudinary
if os.environ.get("cloudinary_cloud_name"):
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get("cloudinary_cloud_name"),
        'API_KEY': os.environ.get("cloudinary_key"),
        'API_SECRET': os.environ.get("cloudinary_secret"),
    }
else:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.getenv("cloudinary_cloud_name_local"),
        'API_KEY': os.getenv("cloudinary_key_local"),
        'API_SECRET': os.getenv("cloudinary_secret_local"),
    }

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"     # Compatibility settings, for cloudinary




# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = '/media/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
